**Q # 2:** NumPy (Numerical Python) is used for Working with arrays (like tables of numbers). Consider an array of any size and values to practice following functions.

In [ ]:
pip install numpy

In [ ]:
import numpy as np

arr_2D = np.array([[1,2,],[2,5]])
arr_1D = np.arange(1,20,4)
arr2_1D = np.arange(10)
arr2_2D = np.arange(1, 5).reshape(2, 2)

print("2D array:\n", arr_2D)
print("1D array using arrange start, stop & step: ", arr_1D)
print("1D array using arrange:", arr2_1D)
print("2D array using arrange & reshape:\n", arr2_2D)

print("2D array with zeros: \n", np.zeros((2,2),dtype=int))
print("2D array with ones: \n", np.ones((3,2)))

print("Shape of an array: ", arr2_2D.shape)
print("Size of an array: ", arr2_2D.size)
print("Data type of an array: ", arr2_2D.dtype)

print("Mean of all elements in array: " , np.mean(arr_1D))
print("Mean along rows:", np.mean(arr_2D, axis=1))
print("Mean along cols:", np.mean(arr_2D, axis=0))

print("Median of array: " , np.median(arr_1D))

print("Standard Deviation of array: " , np.std(arr_1D))

dot_product_result=np.dot(arr_2D,arr2_2D)
print("Dot product of two array are: ",dot_product_result)


2D array:
 [[1 2]
 [2 5]]
1D array using arrange start, stop & step:  [ 1  5  9 13 17]
1D array using arrange: [0 1 2 3 4 5 6 7 8 9]
2D array using arrange & reshape:
 [[1 2]
 [3 4]]
2D array with zeros: 
 [[0 0]
 [0 0]]
2D array with ones: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Shape of an array:  (2, 2)
Size of an array:  4
Data type of an array:  int64
Mean of all elements in array:  9.0
Mean along rows: [1.5 3.5]
Mean along cols: [1.5 3.5]
Median of array:  9.0
Standard Deviation of array:  5.656854249492381
Dot product of two array are:  [[ 7 10]
 [17 24]]


**Q # 3:** Pandas (Data Analysis Library) is used to handle tabular data (like Excel or CSV files). Download [Iris Dataset]( http://archive.ics.uci.edu/ml/datasets/Iris/) and apply following functions.

Import Library & Uploading Dataset

In [ ]:
import pandas as pd
columns = ["sepal_length", "sepal_width", "petal_length", "petal_width", "class"]

df = pd.read_csv("iris.csv", header=None, names=columns)

df

sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
df.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
df.tail()

sepal_length  sepal_width  petal_length  petal_width           class
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   class         150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
df.shape

(150, 5)

In [ ]:
df['col']=df['class']
df.head()

sepal_length  sepal_width  petal_length  petal_width        class  \
0           5.1          3.5           1.4          0.2  Iris-setosa   
1           4.9          3.0           1.4          0.2  Iris-setosa   
2           4.7          3.2           1.3          0.2  Iris-setosa   
3           4.6          3.1           1.5          0.2  Iris-setosa   
4           5.0          3.6           1.4          0.2  Iris-setosa   

           col  
0  Iris-setosa  
1  Iris-setosa  
2  Iris-setosa  
3  Iris-setosa  
4  Iris-setosa

In [ ]:
print("Print First row of dataset\n", df.iloc[0])

print("Print Second row & second column of dataset\n", df.iloc[1, 1])

print("Print First 5 rows & first 5 columns of dataset\n", df.iloc[0:5, 0:5])

Print First row of dataset
 sepal_length            5.1
sepal_width             3.5
petal_length            1.4
petal_width             0.2
class           Iris-setosa
col             Iris-setosa
Name: 0, dtype: object
Print Second row & second column of dataset
 3.0
Print First 5 rows & first 5 columns of dataset
    sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
